CREATE TABLE patients(
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    date_of_birth DATE NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE medical_histories(
    id INT GENERATED BY DEFAULT AS IDENTITY,
    admitted_at TIMESTAMP NOT NULL,
    patient_id INT NOT NULL,
    status VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE medical_histories
    ADD CONSTRAINT fk_medical_histories_patient
    FOREIGN KEY(patient_id) REFERENCES patients(id);


CREATE TABLE treatments(
    id INT GENERATED BY DEFAULT AS IDENTITY,
    type VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE `invoices`(
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `total_amount` DECIMAL(8, 2) NOT NULL,
    `generated_at` TIMESTAMP NOT NULL,
    `payed_at` TIMESTAMP NOT NULL,
    `medical_history_id` INT NOT NULL
    PRIMARY KEY `invoices_id_primary`(`id`);
    CONSTRAINT `invoices_medical_history_id_foreign` FOREIGN KEY(`medical_history_id`) REFERENCES `medical_histories`(`id`);
);

CREATE TABLE `invoice_items`(
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `unit_price` DECIMAL(8, 2) NOT NULL,
    `quantity` INT NOT NULL,
    `total_prince` DECIMAL(8, 2) NOT NULL,
    `invoice_id` INT NOT NULL,
    `tretment_id` INT NOT NULL,
    PRIMARY KEY `invoice_items_id_primary`(`id`);
    CONSTRAINT `invoice_items_tretment_id_foreign` FOREIGN KEY(`tretment_id`) REFERENCES `treatments`(`id`);
    CONSTRAINT `invoice_items_invoice_id_foreign` FOREIGN KEY(`invoice_id`) REFERENCES `invoices`(`id`);
);

